# Generated by Django 4.2.4 on 2023-10-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReserfastAppCrearClientes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_uno', models.CharField(max_length=60)),
                ('nombre_dos', models.CharField(max_length=60)),
                ('apellido_uno', models.CharField(max_length=60)),
                ('apellido_dos', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=12)),
                ('rut', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=150)),
                ('contrasena', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'reserfast_app_crear_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReserfastAppTablaTest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('columna_uno', models.CharField(max_length=200)),
                ('columna_dos', models.CharField(max_length=200)),
                ('columna_tres', models.CharField(max_length=200)),
                ('columna_cuatro', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'reserfast_app_tabla_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('s_primernombrecliente', models.CharField(blank=True, db_column='s_primerNombreCliente', max_length=80, null=True)),
                ('s_segundonombrecliente', models.CharField(blank=True, db_column='s_segundoNombreCliente', max_length=80, null=True)),
                ('s_primerapellidocliente', models.CharField(blank=True, db_column='s_primerApellidoCliente', max_length=80, null=True)),
                ('s_segundoapellidocliente', models.CharField(blank=True, db_column='s_segundoApellidoCliente', max_length=80, null=True)),
                ('s_rut', models.CharField(blank=True, max_length=13, null=True)),
                ('s_email', models.CharField(blank=True, max_length=50, null=True)),
                ('s_contrasena', models.CharField(blank=True, max_length=50, null=True)),
                ('b_activo', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_cliente',
                'ordering': ['s_primernombrecliente'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblGenero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('s_nombregenero', models.CharField(blank=True, db_column='s_nombreGenero', max_length=50, null=True)),
                ('b_activo', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblIngrediente',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('s_nombreingrediente', models.CharField(blank=True, db_column='s_nombreIngrediente', max_length=100, null=True)),
                ('b_activo', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_ingrediente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMenu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('s_titulomenu', models.CharField(blank=True, db_column='s_tituloMenu', max_length=50, null=True)),
                ('s_descripcionmenu', models.CharField(blank=True, db_column='s_descripcionMenu', max_length=1000, null=True)),
                ('i_precio', models.IntegerField(blank=True, null=True)),
                ('b_activo', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMenuingrediente',
            fields=[
                ('id_menuingrediente', models.AutoField(db_column='id_menuIngrediente', primary_key=True, serialize=False)),
                ('b_activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_menuIngrediente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMesa',
            fields=[
                ('id_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('s_descripcionmesa', models.CharField(blank=True, db_column='s_descripcionMesa', max_length=100, null=True)),
                ('d_fechacreacion', models.DateField(blank=True, db_column='d_fechaCreacion', null=True)),
                ('s_ubicacion', models.CharField(blank=True, max_length=30, null=True)),
                ('b_activo', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_mesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPerfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('s_nombreperfil', models.CharField(blank=True, db_column='s_nombrePerfil', max_length=50, null=True)),
                ('b_activo', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblReserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('d_fechainicio', models.DateField(blank=True, db_column='d_fechaInicio', null=True)),
                ('i_totalreserva', models.IntegerField(blank=True, db_column='i_totalReserva', null=True)),
                ('b_activo', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblReservamenu',
            fields=[
                ('id_reservamenu', models.AutoField(db_column='id_reservaMenu', primary_key=True, serialize=False)),
                ('b_activo', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_reservaMenu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblReservamesa',
            fields=[
                ('id_reservamesa', models.AutoField(db_column='id_reservaMesa', primary_key=True, serialize=False)),
                ('b_activo', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_reservaMesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblUsuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('s_nombreusuario', models.CharField(blank=True, db_column='s_nombreUsuario', max_length=80, null=True)),
                ('s_primerapellidousuario', models.CharField(blank=True, db_column='s_primerApellidoUsuario', max_length=80, null=True)),
                ('s_segundoapellidousuario', models.CharField(blank=True, db_column='s_segundoApellidoUsuario', max_length=80, null=True)),
                ('b_activo', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_usuario',
                'managed': False,
            },
        ),
    ]
