# Generated by Django 4.2.4 on 2023-10-29 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserfast_app', '0001_initial'),
    ]

    operations = [
    ]
