# Generated by Django 4.2.4 on 2023-10-29 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserfast_app', '0002_auto_20231029_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblcliente',
            options={'managed': False, 'ordering': ['s_primernombrecliente'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='tblgenero',
            options={'managed': False, 'verbose_name': 'Genero'},
        ),
        migrations.AlterModelOptions(
            name='tblingrediente',
            options={'managed': False, 'verbose_name': 'Ingrediente'},
        ),
        migrations.AlterModelOptions(
            name='tblmenu',
            options={'managed': False, 'verbose_name': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='tblmenuingrediente',
            options={'managed': False, 'verbose_name': 'MenuIngrediente'},
        ),
        migrations.AlterModelOptions(
            name='tblmesa',
            options={'managed': False, 'verbose_name': 'Mesa'},
        ),
        migrations.AlterModelOptions(
            name='tblperfil',
            options={'managed': False, 'verbose_name': 'Perfil'},
        ),
        migrations.AlterModelOptions(
            name='tblreserva',
            options={'managed': False, 'verbose_name': 'Reserva'},
        ),
        migrations.AlterModelOptions(
            name='tblreservamenu',
            options={'managed': False, 'verbose_name': 'ReservaMenu'},
        ),
        migrations.AlterModelOptions(
            name='tblreservamesa',
            options={'managed': False, 'verbose_name': 'ReservaMesa'},
        ),
        migrations.AlterModelOptions(
            name='tblusuario',
            options={'managed': False, 'verbose_name': 'Usuario'},
        ),
    ]
