# Generated by Django 5.2.1 on 2025-07-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserfast_app', '0003_alter_tblcliente_options_alter_tblgenero_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_nombreMenu', models.CharField(max_length=100)),
                ('s_imagen', models.ImageField(blank=True, null=True, upload_to='menus/')),
                ('b_activo', models.BooleanField(default=True)),
            ],
        ),
    ]
