# Generated by Django 5.2.1 on 2025-07-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserfast_app', '0006_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='s_imagen',
        ),
    ]
