# Generated by Django 5.2.1 on 2025-07-24 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserfast_app', '0007_remove_menu_s_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
